#!/bin/bash

EMACS_VER=25.3

sudo apt-get install build-essential
sudo apt-get build-dep emacs24

TMPDIR=`mktemp -d`
cd $TMPDIR

wget http://ftp.gnu.org/gnu/emacs/emacs-$EMACS_VER.tar.gz
tar -xf emacs-$EMACS_VER.tar.gz
cd emacs-$EMACS_VER
./configure
make
sudo make install

rm -rf $TMPDIR
