#!/usr/bin/env bash

sudo apt-get --no-install-recommends -yqq install \
  bash-completion \
  build-essential \
  cmake \
  libcurl4  \
  libcurl4-openssl-dev  \
  libssl-dev  \
  libxml2 \
  libxml2-dev  \
  libssl1.1 \
  pkg-config \
  ca-certificates \
  xclip

LPASS_REPO_DIR=~/.lpass

git clone https://github.com/LastPass/lastpass-cli $LPASS_REPO_DIR

cd $LPASS_REPO_DIR
make
sudo make install

cd ~
rm -rf $LPASS_REPO_DIR
